// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsvPXJ6ndekXerqIUgMXN7YNtX06MG6jc',
    appId: '1:1059068225676:web:98e7a357c3981a324e73a9',
    messagingSenderId: '1059068225676',
    projectId: 'myrwa-india',
    storageBucket: 'myrwa-india.firebasestorage.app',
    authDomain: 'myrwa-india.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGAcQbXwYJoZkUrFbAjVSp8H3uzgn6KkA',
    appId: '1:1059068225676:android:541077152d4e8be74e73a9',
    messagingSenderId: '1059068225676',
    projectId: 'myrwa-india',
    storageBucket: 'myrwa-india.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBffy-WWxudAdvmu_U_emm60tjvpRT5k4Y',
    appId: '1:1059068225676:ios:8d8594b21241b3084e73a9',
    messagingSenderId: '1059068225676',
    projectId: 'myrwa-india',
    storageBucket: 'myrwa-india.firebasestorage.app',
    iosBundleId: 'com.myrwa.india',
  );
}
